site_name: Arabian vACC - Library
site_url: ""
theme:
  name: material
  font:
    text: Mulish
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/arabianvacc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Fk9Wspw
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/arabianvacc
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/arabianvacc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/arabianvacc
    - icon: fontawesome/brands/github
      link: https://github.com/arabian-vacc

copyright: Copyright &copy; 2024 Arabian vACC
