site_name: Arabian vACC - Library
site_url: https://library.arabian-vacc.com
repo_url: https://github.com/arabian-vacc/library
repo_name: arabian-vacc/library
edit_uri: ""
copyright: ""

theme:
  name: material
  custom_dir: overrides
  font:
    text: Mulish
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange

markdown_extensions:
  - meta
  - admonition
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - abbr
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/arabianvacc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Fk9Wspw
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/arabianvacc
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/arabianvacc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/arabianvacc
    - icon: fontawesome/brands/github
      link: https://github.com/arabian-vacc

plugins:
    - search
    - awesome-pages

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

copyright: The content provided by the Arabian vACC on this website is for Flight Simulation purposes only and should not be used for real-world navigation.
